"use client";

import { ComponentHeader } from "@/components/ComponentHeader";
import LockDimFeactureOverlay from "@/components/LockDimFeactureOverlay";
import { Lightbulb } from "lucide-react";

type Recommendation = {
  title: string;
  description: string;
};

const STAFFING_RECOMMENDATIONS: Recommendation[] = [
  {
    title: "Peak Overload (10am – 11am):",
    description:
      "Aisha Patel handles 55 orders/hour alone during this window. Consider adding 1 additional staff member during this period.",
  },
  {
    title: "Evening surge (6pm – 7pm):",
    description:
      "Evening team hit 42 orders/hour with only 2 staff. Recommend rotating a morning barista to cover this window.",
  },
  {
    title: "Top Performer:",
    description:
      "Aisha Patel leads with 255 orders at a 3.9m avg fulfillment time and a 4.9 rating. Consider a mentoring program.",
  },
];

export default function StaffingRecommendations() {
  return (
    <div className="relative  rounded-2xl border border-amber-100 bg-amber-50/40 shadow-sm p-5">
      <LockDimFeactureOverlay component_name="Staffing Recommendations" />

      {/* Header */}
      <div className="flex items-start justify-between mb-5">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-amber-50 flex items-center justify-center shrink-0">
            <Lightbulb size={15} className="text-amber-600" />
          </div>

          <ComponentHeader
            title="Staffing Recommendations"
            subHeader="Optimize workforce allocation based on performance analysis"
            titleColor="text-amber-900"
          />
        </div>
      </div>

      {/* Recommendations */}
      <div className="space-y-2.5">
        {STAFFING_RECOMMENDATIONS.map((item, index) => (
          <div
            key={index}
            className="flex items-start gap-3 rounded-xl border border-amber-200  px-3.5 py-3 transition-all duration-200 hover:bg-amber-50"
          >
            {/* Icon dot */}
            {/* <div className="flex w-7 h-7 shrink-0 items-center justify-center rounded-full bg-amber-100 mt-0.5">
              <span className="text-[11px] font-bold text-amber-600">
                {index + 1}
              </span>
            </div> */}

            {/* Text */}
            <p className="text-xs text-gray-700 leading-relaxed">
              <span className="font-semibold text-gray-900">{item.title}</span>{" "}
              {item.description}
            </p>
          </div>
        ))}
      </div>

      {/* Footer */}
      <div className="mt-4 border-t border-gray-100 pt-4">
        <p className="text-[11px] text-gray-400">
          Staffing recommendations are generated by analyzing hourly order
          volume, employee performance, staffing levels, and fulfillment
          efficiency to help optimize workforce allocation.
        </p>
      </div>
    </div>
  );
}
