"use client";

import { useEffect, useState, useMemo } from "react";
import { Loader2, Radar, Info } from "lucide-react";
import type { DateRangeValue } from "@/components/dashboardComponents/staffDash/DateRangeFilter";
import { formatCurrencySymbol } from "@/utils/helper";
import { useCurrency } from "@/providers/CurrencyContext";
interface AggregatedMetrics {
  totalRevenue: number;
  totalSales: number;
  totalOrders: number;
  totalBills: number;
}

// ── Types ───────────────────────────────────────────────────────────────────

interface PerformanceRadarProps {
  employeeId: string;
  avgTime: string | null;
  dateRange: DateRangeValue;
}

interface EmployeeSales {
  totalRevenue: number;
  totalSales: number;
}

interface EmployeeBills {
  totalBills: number;
  customerCount: number;
  refundedBills: number;
  refundRate: number;
}

interface RadarDataPoint {
  label: string;
  score: number;
  rawValue: number;
  unit: string;
  description: string;
  benchmarkValue: number; // ← the max value used for normalization
  benchmarkUnit: string; // ← formatted benchmark for display
}

const RADAR_SIZE = 360;
const CENTER = RADAR_SIZE / 2;
const RADIUS = RADAR_SIZE * 0.3;

// const METRIC_INFO: Record<string, { label: string; description: string }> = {
//   Revenue: {
//     label: "Revenue",
//     description: "Total revenue generated by the employee",
//   },
//   Orders: {
//     label: "Orders",
//     description: "Total number of orders/bills handled",
//   },
//   "Avg Order": {
//     label: "Avg Order",
//     description: "Revenue ÷ Orders — measures transaction quality",
//   },
//   Customers: {
//     label: "Customers",
//     description: "Unique customers served by the employee",
//   },
//   "Shift Time": {
//     label: "Shift Time",
//     description: "Average shift duration from employee stat card",
//   },
//   Accuracy: {
//     label: "Accuracy",
//     description: "100% − Refund Rate — measures transaction accuracy",
//   },
// };

// ── Helper Functions ────────────────────────────────────────────────────────

function parseAvgShiftTime(raw: string | null): number {
  if (!raw || raw === "—") return 0;
  const hourMatch = raw.match(/(\d+)\s*h/);
  const minMatch = raw.match(/(\d+)\s*m/);
  const colonMatch = raw.match(/^(\d+):(\d+)$/);
  const totalMinutes =
    (hourMatch ? parseInt(hourMatch[1]) * 60 : 0) +
    (minMatch ? parseInt(minMatch[1]) : 0) +
    (colonMatch ? parseInt(colonMatch[1]) * 60 + parseInt(colonMatch[2]) : 0);
  return totalMinutes > 0 ? totalMinutes : 0;
}

function formatAvgShiftTime(minutes: number): string {
  if (minutes <= 0) return "—";
  const h = Math.floor(minutes / 60);
  const m = Math.round(minutes % 60);
  if (h > 0 && m > 0) return `${h}h ${m}m`;
  if (h > 0) return `${h}h`;
  return `${m}m`;
}

function formatCurrency(value: number): string {
  if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `$${(value / 1000).toFixed(1)}K`;
  return `$${value.toFixed(2)}`;
}

function formatOrders(value: number): string {
  if (value >= 1000) return `${(value / 1000).toFixed(1)}K`;
  return value.toString();
}

function formatPercentage(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

function formatRatioValue(orders: number, sales: number): string {
  if (sales === 0) return "—";
  return `${(orders / sales).toFixed(2)}x`;
}

// ── Hexagon Radar Chart ─────────────────────────────────────────────────────

function RadarChart({
  data,
  hoveredIndex,
  onHover,
}: {
  data: RadarDataPoint[];
  hoveredIndex: number | null;
  onHover: (index: number | null, event?: React.MouseEvent) => void;
}) {
  const numVertices = data.length;
  const angleStep = (2 * Math.PI) / numVertices;
  const offset = -Math.PI / 2;

  // Outer hexagon points (benchmark = 100)
  const outerPoints = Array.from({ length: numVertices }, (_, i) => {
    const angle = offset + i * angleStep;
    const x = CENTER + RADIUS * Math.cos(angle);
    const y = CENTER + RADIUS * Math.sin(angle);
    return `${x},${y}`;
  }).join(" ");

  // Inner filled polygon
  const innerPoints = data.map((point, i) => {
    const angle = offset + i * angleStep;
    const scoreRadius = (point.score / 100) * RADIUS;
    const x = CENTER + scoreRadius * Math.cos(angle);
    const y = CENTER + scoreRadius * Math.sin(angle);
    return { x, y };
  });

  const innerPointsStr = innerPoints.map((p) => `${p.x},${p.y}`).join(" ");

  // Axis data
  const axes = data.map((point, i) => {
    const angle = offset + i * angleStep;
    const endX = CENTER + RADIUS * Math.cos(angle);
    const endY = CENTER + RADIUS * Math.sin(angle);
    const labelRadius = RADIUS + 38;
    const labelX = CENTER + labelRadius * Math.cos(angle);
    const labelY = CENTER + labelRadius * Math.sin(angle);
    return { endX, endY, labelX, labelY, point, index: i };
  });

  return (
    <svg
      width={RADAR_SIZE}
      height={RADAR_SIZE}
      viewBox={`0 0 ${RADAR_SIZE} ${RADAR_SIZE}`}
      className="shrink-0"
    >
      {/* Outer hexagon (benchmark) */}
      <polygon
        points={outerPoints}
        fill="none"
        stroke="#e5e7eb"
        strokeWidth={1.5}
      />

      {/* Inner grid hexagons (25%, 50%, 75%) */}
      {[0.25, 0.5, 0.75].map((scale) => {
        const gridPoints = Array.from({ length: numVertices }, (_, i) => {
          const angle = offset + i * angleStep;
          const x = CENTER + RADIUS * scale * Math.cos(angle);
          const y = CENTER + RADIUS * scale * Math.sin(angle);
          return `${x},${y}`;
        }).join(" ");
        return (
          <polygon
            key={scale}
            points={gridPoints}
            fill="none"
            stroke="#f3f4f6"
            strokeWidth={1}
          />
        );
      })}

      {/* Axis lines */}
      {axes.map((axis) => (
        <line
          key={`axis-${axis.index}`}
          x1={CENTER}
          y1={CENTER}
          x2={axis.endX}
          y2={axis.endY}
          stroke="#e5e7eb"
          strokeWidth={1}
        />
      ))}

      {/* Filled inner polygon */}
      <polygon
        points={innerPointsStr}
        fill="rgba(59, 130, 246, 0.15)"
        stroke="#3b82f6"
        strokeWidth={2}
      />

      {/* Data points with hover tooltip areas */}
      {innerPoints.map((p, i) => (
        <g key={`point-group-${i}`}>
          {/* Invisible larger hit area for hover */}
          <circle
            cx={p.x}
            cy={p.y}
            r={12}
            fill="transparent"
            className="cursor-pointer"
            onMouseEnter={(e) => onHover(i, e)}
            onMouseLeave={() => onHover(null)}
          />
          {/* Visible dot */}
          <circle
            cx={p.x}
            cy={p.y}
            r={hoveredIndex === i ? 5 : 3.5}
            fill={hoveredIndex === i ? "#2563eb" : "#3b82f6"}
            stroke="white"
            strokeWidth={2}
            className="transition-all duration-150"
            onMouseEnter={(e) => onHover(i, e)}
            onMouseLeave={() => onHover(null)}
          />
        </g>
      ))}

      {/* Metric labels */}
      {axes.map((axis) => (
        <text
          key={`label-${axis.index}`}
          x={axis.labelX}
          y={axis.labelY}
          textAnchor="middle"
          dominantBaseline="middle"
          className="text-[11px] fill-gray-600 font-medium"
          style={{ fontSize: "11px", fontFamily: "inherit" }}
        >
          {axis.point.label}
        </text>
      ))}

      {/* Center label */}
      {/* <text
        x={CENTER}
        y={CENTER}
        textAnchor="middle"
        dominantBaseline="middle"
        className="text-[10px] fill-gray-400"
        style={{ fontSize: "10px", fontFamily: "inherit" }}
      >
        Score
      </text> */}
    </svg>
  );
}

// ── Tooltip Component ───────────────────────────────────────────────────────

function MetricTooltip({
  data,
  index,
  position,
}: {
  data: RadarDataPoint[];
  index: number;
  position: { x: number; y: number };
}) {
  const metric = data[index];
  if (!metric) return null;

  const isRefund = metric.label === "Refund Rate";

  return (
    <div
      className="absolute z-50 bg-white rounded-xl px-4 py-3 shadow-lg border border-gray-100 pointer-events-none min-w-44"
      style={{
        left: `${position.x}px`,
        top: `${position.y}px`,
        transform: "translate(-50%, -110%)",
      }}
    >
      <p className="text-sm font-bold text-gray-900 mb-2">{metric.label}</p>

      <div className="space-y-1.5">
        {/* Score */}
        <div className="flex items-center justify-between gap-6 text-xs">
          <span className="text-gray-400">Score</span>
          <span className="font-bold text-blue-600">{metric.score} / 100</span>
        </div>

        {/* Employee value */}
        <div className="flex items-center justify-between gap-6 text-xs">
          <span className="text-gray-400">Value</span>
          <span className="font-semibold text-gray-900">{metric.unit}</span>
        </div>

        {/* Benchmark — skip for Refund Rate since lower is better */}
        {!isRefund && (
          <div className="flex items-center justify-between gap-6 text-xs">
            <span className="text-gray-400">Benchmark</span>
            <span className="font-semibold text-violet-600">
              {metric.benchmarkUnit}
            </span>
          </div>
        )}

        {/* Visual progress bar */}
        <div className="pt-1">
          <div className="h-1.5 w-full bg-gray-100 rounded-full overflow-hidden">
            <div
              className={`h-full rounded-full transition-all ${
                metric.score >= 75
                  ? "bg-green-500"
                  : metric.score >= 50
                    ? "bg-blue-500"
                    : metric.score >= 25
                      ? "bg-amber-500"
                      : "bg-red-400"
              }`}
              style={{ width: `${metric.score}%` }}
            />
          </div>
        </div>

        {/* Description */}
        <div className="border-t border-gray-100 pt-1.5 mt-1">
          <p className="text-[10px] text-gray-400 leading-tight">
            {metric.description}
          </p>
        </div>
      </div>
    </div>
  );
}

// ── Main Component ──────────────────────────────────────────────────────────

export default function PerformanceRadar({
  employeeId,
  avgTime,
  dateRange,
}: PerformanceRadarProps) {
  const { currency } = useCurrency();
  const [sales, setSales] = useState<EmployeeSales | null>(null);
  const [billsData, setBillsData] = useState<EmployeeBills | null>(null);
  const [totalCustomers, setTotalCustomers] = useState(50);
  const [totalOrders, setTotalOrders] = useState(0);
  const [aggregatedMetrics, setAggregatedMetrics] =
    useState<AggregatedMetrics | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [hoveredIndex, setHoveredIndex] = useState<number | null>(null);
  const [tooltipPos, setTooltipPos] = useState({ x: 0, y: 0 });
  const [showBaseline, setShowBaseline] = useState(false);

  // Fetch data
  useEffect(() => {
    if (!employeeId) return;

    const fetchData = async () => {
      setLoading(true);
      setError(null);
      try {
        const [salesRes, billsRes, customersRes, ticketsRes, aggregatedRes] =
          await Promise.all([
            fetch(
              `/api/staff/sales-by-employee/${employeeId}?startDate=${dateRange.startDate}&endDate=${dateRange.endDate}`,
            ),
            fetch(
              `/api/staff/bills/${employeeId}?startDate=${dateRange.startDate}&endDate=${dateRange.endDate}`,
            ),
            fetch("/api/customers"),
            fetch(
              `/api/staff/${employeeId}/tickets?startDate=${dateRange.startDate}&endDate=${dateRange.endDate}`,
            ),
            fetch(
              `/api/staff/aggregated-metrics?startDate=${dateRange.startDate}&endDate=${dateRange.endDate}`,
            ),
          ]);

        if (!salesRes.ok) throw new Error("Failed to load sales data");
        if (!billsRes.ok) throw new Error("Failed to load bill data");

        const salesJson = await salesRes.json();
        const billsJson = await billsRes.json();

        if (ticketsRes.ok) {
          const ticketsJson = await ticketsRes.json();
          setTotalOrders(ticketsJson?.data?.totalCount ?? 0);
        }

        if (customersRes.ok) {
          const customersJson = await customersRes.json();
          const users = customersJson?.data?.users ?? [];
          if (users.length > 0) {
            setTotalCustomers(users.length);
          }
        }

        const empData = salesJson?.data?.employeeData;
        if (empData) {
          setSales({
            totalRevenue: empData.totalRevenue ?? 0,
            totalSales: empData.totalSales ?? 0,
          });
        } else {
          setSales({ totalRevenue: 0, totalSales: 0 });
        }

        if (billsJson?.data) {
          setBillsData({
            totalBills: billsJson.data.totalBills ?? 0,
            customerCount: billsJson.data.customerCount ?? 0,
            refundedBills: billsJson.data.refundedBills ?? 0,
            refundRate: billsJson.data.refundRate ?? 0,
          });
        } else {
          setBillsData({
            totalBills: 0,
            customerCount: 0,
            refundedBills: 0,
            refundRate: 0,
          });
        }

        // Set aggregated metrics from API
        if (aggregatedRes.ok) {
          const aggregatedJson = await aggregatedRes.json();
          setAggregatedMetrics(aggregatedJson);
        }
      } catch (err) {
        setError(
          err instanceof Error
            ? err.message
            : "Failed to load performance data",
        );
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, [employeeId, dateRange.startDate, dateRange.endDate]);

  // Compute normalized scores
  const chartData: RadarDataPoint[] = useMemo(() => {
    if (!sales || !billsData) return [];

    const totalRevenue = sales.totalRevenue;
    const totalSalesCount = sales.totalSales;
    const totalOrdersCount = totalOrders;
    const avgOrderValue =
      totalSalesCount > 0 ? totalRevenue / totalSalesCount : 0;
    const customerCount = billsData.customerCount;
    const avgShiftMinutes = parseAvgShiftTime(avgTime);
    const refundRate = billsData.refundRate;
    const ordersToSalesRatio =
      totalSalesCount > 0 ? totalOrdersCount / totalSalesCount : 0;

    // ── Benchmark (max) values ─────────────────────────────────────────────
    const maxRevenue = Math.max(
      totalRevenue,
      aggregatedMetrics?.totalRevenue ?? 0,
      1,
    );
    const maxSales = Math.max(
      totalSalesCount,
      aggregatedMetrics?.totalBills ?? 0,
      1,
    );
    const maxOrders = Math.max(
      totalOrdersCount,
      aggregatedMetrics?.totalOrders ?? 0,
      1,
    );
    const maxAvgOrderValue = Math.max(avgOrderValue, 100, 1);
    const maxCustomerCount = Math.max(customerCount, totalCustomers, 1);
    const maxShiftMinutes = Math.max(avgShiftMinutes, 6000);

    const revenueScore = Math.min(100, (totalRevenue / maxRevenue) * 100);
    const salesScore = Math.min(100, (totalSalesCount / maxSales) * 100);
    const ordersScore = Math.min(100, (totalOrdersCount / maxOrders) * 100);
    const avgOrderScore = Math.min(
      100,
      (avgOrderValue / maxAvgOrderValue) * 100,
    );
    const customerScore = Math.min(
      100,
      (customerCount / maxCustomerCount) * 100,
    );
    const shiftTimeScore = Math.min(
      100,
      (avgShiftMinutes / maxShiftMinutes) * 100,
    );
    const refundScore = Math.max(0, 100 - refundRate * 100);
    const ordToSalesScore = Math.min(100, (ordersToSalesRatio / 3) * 100);

    return [
      {
        label: "Revenue",
        score: Math.round(revenueScore),
        rawValue: totalRevenue,
        unit: formatCurrencySymbol(
          totalRevenue,
          currency.symbol,
          currency.locale,
        ),
        description: "Total revenue generated by the employee",
        benchmarkValue: maxRevenue,
        benchmarkUnit: formatCurrencySymbol(
          maxRevenue,
          currency.symbol,
          currency.locale,
        ),
      },
      {
        label: "Orders",
        score: Math.round(ordersScore),
        rawValue: totalOrdersCount,
        unit: formatOrders(totalOrdersCount),
        description: "Total number of invoices/tickets taken",
        benchmarkValue: maxOrders,
        benchmarkUnit: formatOrders(maxOrders),
      },
      {
        label: "Sales",
        score: Math.round(salesScore),
        rawValue: totalSalesCount,
        unit: formatOrders(totalSalesCount),
        description: "Total number of orders/bills handled",
        benchmarkValue: maxSales,
        benchmarkUnit: formatOrders(maxSales),
      },
      {
        label: "Avg Sales",
        score: Math.round(avgOrderScore),
        rawValue: avgOrderValue,
        unit: formatCurrencySymbol(
          avgOrderValue,
          currency.symbol,
          currency.locale,
        ),
        description: "Revenue ÷ Orders — measures transaction quality",
        benchmarkValue: maxAvgOrderValue,
        benchmarkUnit: formatCurrencySymbol(
          maxAvgOrderValue,
          currency.symbol,
          currency.locale,
        ),
      },
      {
        label: "Ord-to-Sales",
        score: Math.round(ordToSalesScore),
        rawValue: ordersToSalesRatio,
        unit: formatRatioValue(totalOrdersCount, totalSalesCount),
        description:
          "Orders ÷ Sales — measures how many tickets were raised per bill processed",
        benchmarkValue: 3,
        benchmarkUnit: "3.00x",
      },
      {
        label: "Customers",
        score: Math.round(customerScore),
        rawValue: customerCount,
        unit: customerCount.toString(),
        description: "Unique customers served by the employee",
        benchmarkValue: maxCustomerCount,
        benchmarkUnit: maxCustomerCount.toString(),
      },
      {
        label: "Shift Time",
        score: Math.round(shiftTimeScore),
        rawValue: avgShiftMinutes,
        unit: formatAvgShiftTime(avgShiftMinutes),
        description:
          "Average shift duration compared to the longest shift in the period",
        benchmarkValue: maxShiftMinutes,
        benchmarkUnit: formatAvgShiftTime(maxShiftMinutes),
      },
      {
        label: "Refund Rate",
        score: Math.round(refundScore),
        rawValue: refundRate,
        unit: formatPercentage(refundRate),
        description:
          "Refunded Orders ÷ Total Orders — lower rate = higher score",
        benchmarkValue: 0, // lower is better — no meaningful "max benchmark"
        benchmarkUnit: "0.0%",
      },
    ];
  }, [
    sales,
    billsData,
    avgTime,
    totalCustomers,
    totalOrders,
    aggregatedMetrics,
    currency,
  ]);

  // Handle hover for tooltip positioning
  const handleHover = (index: number | null, event?: React.MouseEvent) => {
    setHoveredIndex(index);
    if (index !== null && event) {
      // Position tooltip relative to the mouse cursor
      const rect = event.currentTarget
        .closest(".relative")
        ?.getBoundingClientRect();
      if (rect) {
        setTooltipPos({
          x: event.clientX - rect.left + 20,
          y: event.clientY - rect.top - 10,
        });
      } else {
        setTooltipPos({ x: event.clientX + 20, y: event.clientY - 10 });
      }
    }
  };

  // ── Loading state ─────────────────────────────────────────────────────────

  if (loading) {
    return (
      <div
        className={`bg-white rounded-2xl border border-gray-100 shadow-sm p-4 sm:p-6 mb-6 `}
      >
        <div className="flex items-center gap-3 mb-6">
          <div className="w-7 h-7 rounded-lg bg-violet-50 flex items-center justify-center">
            <Radar size={16} className="text-violet-500" />
          </div>
          <div>
            <h2 className="text-sm font-semibold text-gray-900">
              Performance Radar
            </h2>
            <p className="text-[11px] text-gray-400 mt-px">
              Loading metrics...
            </p>
          </div>
        </div>
        <div className="flex items-center justify-center py-12">
          <Loader2 size={20} className="animate-spin text-violet-500" />
        </div>
      </div>
    );
  }

  // ── Error state ───────────────────────────────────────────────────────────

  if (error) {
    return (
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 ">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-7 h-7 rounded-lg bg-violet-50 flex items-center justify-center">
            <Radar size={16} className="text-violet-500" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-gray-900">
              Performance Radar
            </h2>
            <p className="text-[11px] text-gray-400 mt-px">
              Unable to load data
            </p>
          </div>
        </div>

        <div className="text-center py-8">
          <div className="w-12 h-12 rounded-full bg-red-50 flex items-center justify-center mx-auto mb-3">
            <svg
              className="w-6 h-6 text-red-400"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4.5c-.77-.833-2.694-.833-3.464 0L3.34 16.5c-.77.833.192 2.5 1.732 2.5z"
              />
            </svg>
          </div>
          <p className="text-sm font-medium text-gray-500">{error}</p>
          <button
            onClick={() => {
              setLoading(true);
              setError(null);
              const fetchAgain = async () => {
                try {
                  const [salesRes, billsRes] = await Promise.all([
                    fetch(
                      `/api/staff/sales-by-employee/${employeeId}?startDate=${dateRange.startDate}&endDate=${dateRange.endDate}`,
                    ),
                    fetch(
                      `/api/staff/bills/${employeeId}?startDate=${dateRange.startDate}&endDate=${dateRange.endDate}`,
                    ),
                  ]);
                  if (!salesRes.ok) throw new Error("Failed");
                  if (!billsRes.ok) throw new Error("Failed");
                  const salesJson = await salesRes.json();
                  const billsJson = await billsRes.json();
                  const empData = salesJson?.data?.employeeData;
                  setSales(
                    empData
                      ? {
                          totalRevenue: empData.totalRevenue ?? 0,
                          totalSales: empData.totalSales ?? 0,
                        }
                      : { totalRevenue: 0, totalSales: 0 },
                  );
                  setBillsData(
                    billsJson?.data
                      ? {
                          totalBills: billsJson.data.totalBills ?? 0,
                          customerCount: billsJson.data.customerCount ?? 0,
                          refundedBills: billsJson.data.refundedBills ?? 0,
                          refundRate: billsJson.data.refundRate ?? 0,
                        }
                      : {
                          totalBills: 0,
                          customerCount: 0,
                          refundedBills: 0,
                          refundRate: 0,
                        },
                  );
                } catch {
                  setError("Failed to load performance data");
                } finally {
                  setLoading(false);
                }
              };
              fetchAgain();
            }}
            className="mt-3 px-4 py-1.5 text-xs font-medium text-white bg-violet-500 hover:bg-violet-600 rounded-lg transition-colors"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  // ── Empty state ───────────────────────────────────────────────────────────

  if (chartData.length === 0) {
    return (
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
        <div className="flex items-center gap-3 mb-6">
          <div className="w-7 h-7 rounded-lg bg-violet-50 flex items-center justify-center">
            <Radar size={16} className="text-violet-500" />
          </div>

          <div>
            <h2 className="text-sm font-bold text-gray-900">
              Performance Radar
            </h2>

            <p className="text-[11px] text-gray-400 mt-px">No data available</p>
          </div>
        </div>

        <div className="text-center py-8">
          <div className="w-12 h-12 rounded-full bg-gray-50 flex items-center justify-center mx-auto mb-3">
            <Radar size={24} className="text-gray-300" />
          </div>
          <p className="text-sm font-medium text-gray-500">
            No performance data found
          </p>
          <p className="text-xs text-gray-400 mt-1">
            No sales or billing data for this period
          </p>
        </div>
      </div>
    );
  }

  // ── Calculate average score ───────────────────────────────────────────────

  const avgScore = Math.round(
    chartData.reduce((sum, d) => sum + d.score, 0) / chartData.length,
  );

  // ── Render ────────────────────────────────────────────────────────────────

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
      {/* Header */}
      <div className="flex items-center justify-between ">
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 rounded-lg bg-violet-50 flex items-center justify-center">
            <Radar size={16} className="text-violet-500" />
          </div>

          <div>
            <h2 className="text-sm font-bold text-gray-900">
              Performance Radar
            </h2>

            <p className="text-[11px] text-gray-400 mt-px">
              Employee&lsquo;s Performance Radar for {dateRange.startDate} to{" "}
              {dateRange.endDate}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowBaseline(!showBaseline)}
            className="p-1.5 rounded-lg hover:bg-gray-100 transition-colors"
            title="How metrics are calculated"
          >
            <Info size={15} className="text-gray-400" />
          </button>
          <div className="flex items-center gap-1.5 bg-violet-50 px-3 py-1.5 rounded-lg">
            <span className="text-[11px] text-gray-500 font-medium">
              Avg Score
            </span>
            <span className="text-sm font-bold text-violet-600">
              {avgScore}
            </span>
          </div>
        </div>
      </div>

      {/* Baseline info panel */}
      {showBaseline && (
        <div className=" p-3 rounded-xl bg-gray-50 border border-gray-100">
          <p className="text-[11px] font-semibold text-gray-700 mb-2">
            How Scores Are Calculated
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-2 gap-2">
            {chartData.map((metric) => (
              <div
                key={metric.label}
                className="text-[10px] text-gray-500 leading-relaxed"
              >
                <span className="font-medium text-gray-700">
                  {metric.label}
                </span>
                : {metric.description}
              </div>
            ))}
          </div>
          <p className="text-[10px] text-gray-400 mt-2 border-t border-gray-200 pt-2">
            Each metric is normalized to a 0–100 scale. The outer hexagon
            represents the maximum benchmark score (100). Higher values indicate
            better performance.
          </p>
        </div>
      )}

      {/* Radar chart centered */}
      <div className="relative flex justify-center mb-1">
        <RadarChart
          data={chartData}
          hoveredIndex={hoveredIndex}
          onHover={handleHover}
        />
        {hoveredIndex !== null && (
          <MetricTooltip
            data={chartData}
            index={hoveredIndex}
            position={tooltipPos}
          />
        )}
      </div>
    </div>
  );
}
