import { CurrencyConfig } from "@/lib/config/store";

/**
 * Every currency the app offers, one row per issuing country.
 *
 * Generated from ICU data (`Intl.DisplayNames` for the names,
 * `Intl.NumberFormat` for the narrow symbols) so spellings and symbols match
 * what the platform itself would print, rather than being hand-typed.
 *
 * `countryCode` is ISO 3166-1 alpha-2, which is what flagcdn keys its flags
 * by. Shared currencies — the euro, the CFA francs, the East Caribbean dollar —
 * appear once under a representative country.
 */
export interface CurrencyOption extends CurrencyConfig {
  /** Currency name, e.g. "Nepalese Rupee". */
  name: string;
  /** Country name, for search and the sub-label. */
  country: string;
  /** ISO 3166-1 alpha-2, lowercased for flagcdn. */
  countryCode: string;
}

export const CURRENCY_OPTIONS: CurrencyOption[] = [
  {
    code: "AFN",
    symbol: "؋",
    name: "Afghan Afghani",
    country: "Afghanistan",
    countryCode: "af",
    locale: "en-AF",
  },
  {
    code: "ALL",
    symbol: "Lek",
    name: "Albanian Lek",
    country: "Albania",
    countryCode: "al",
    locale: "en-AL",
  },
  {
    code: "DZD",
    symbol: "دج",
    name: "Algerian Dinar",
    country: "Algeria",
    countryCode: "dz",
    locale: "en-DZ",
  },
  {
    code: "AOA",
    symbol: "Kz",
    name: "Angolan Kwanza",
    country: "Angola",
    countryCode: "ao",
    locale: "en-AO",
  },
  {
    code: "ARS",
    symbol: "$",
    name: "Argentine Peso",
    country: "Argentina",
    countryCode: "ar",
    locale: "en-AR",
  },
  {
    code: "AMD",
    symbol: "֏",
    name: "Armenian Dram",
    country: "Armenia",
    countryCode: "am",
    locale: "en-AM",
  },
  {
    code: "AUD",
    symbol: "$",
    name: "Australian Dollar",
    country: "Australia",
    countryCode: "au",
    locale: "en-AU",
  },
  {
    code: "AZN",
    symbol: "₼",
    name: "Azerbaijani Manat",
    country: "Azerbaijan",
    countryCode: "az",
    locale: "en-AZ",
  },
  {
    code: "BHD",
    symbol: "BD",
    name: "Bahraini Dinar",
    country: "Bahrain",
    countryCode: "bh",
    locale: "en-BH",
  },
  {
    code: "BDT",
    symbol: "৳",
    name: "Bangladeshi Taka",
    country: "Bangladesh",
    countryCode: "bd",
    locale: "bn-BD",
  },
  {
    code: "BBD",
    symbol: "$",
    name: "Barbadian Dollar",
    country: "Barbados",
    countryCode: "bb",
    locale: "en-BB",
  },
  {
    code: "BYN",
    symbol: "Br",
    name: "Belarusian Ruble",
    country: "Belarus",
    countryCode: "by",
    locale: "en-BY",
  },
  {
    code: "BZD",
    symbol: "BZ$",
    name: "Belize Dollar",
    country: "Belize",
    countryCode: "bz",
    locale: "en-BZ",
  },
  {
    code: "BMD",
    symbol: "$",
    name: "Bermudan Dollar",
    country: "Bermuda",
    countryCode: "bm",
    locale: "en-BM",
  },
  {
    code: "BTN",
    symbol: "Nu.",
    name: "Bhutanese Ngultrum",
    country: "Bhutan",
    countryCode: "bt",
    locale: "en-BT",
  },
  {
    code: "BOB",
    symbol: "$b",
    name: "Bolivian Boliviano",
    country: "Bolivia",
    countryCode: "bo",
    locale: "en-BO",
  },
  {
    code: "BAM",
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    country: "Bosnia & Herzegovina",
    countryCode: "ba",
    locale: "en-BA",
  },
  {
    code: "BWP",
    symbol: "P",
    name: "Botswanan Pula",
    country: "Botswana",
    countryCode: "bw",
    locale: "en-BW",
  },
  {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    country: "Brazil",
    countryCode: "br",
    locale: "en-BR",
  },
  {
    code: "BND",
    symbol: "$",
    name: "Brunei Dollar",
    country: "Brunei",
    countryCode: "bn",
    locale: "en-BN",
  },
  {
    code: "BGN",
    symbol: "лв",
    name: "Bulgarian Lev",
    country: "Bulgaria",
    countryCode: "bg",
    locale: "en-BG",
  },
  {
    code: "BIF",
    symbol: "FBu",
    name: "Burundian Franc",
    country: "Burundi",
    countryCode: "bi",
    locale: "en-BI",
  },
  {
    code: "KHR",
    symbol: "៛",
    name: "Cambodian Riel",
    country: "Cambodia",
    countryCode: "kh",
    locale: "en-KH",
  },
  {
    code: "XAF",
    symbol: "FCFA",
    name: "Central African CFA Franc",
    country: "Cameroon",
    countryCode: "cm",
    locale: "en-CM",
  },
  {
    code: "CAD",
    symbol: "$",
    name: "Canadian Dollar",
    country: "Canada",
    countryCode: "ca",
    locale: "en-CA",
  },
  {
    code: "KYD",
    symbol: "$",
    name: "Cayman Islands Dollar",
    country: "Cayman Islands",
    countryCode: "ky",
    locale: "en-KY",
  },
  {
    code: "CLP",
    symbol: "$",
    name: "Chilean Peso",
    country: "Chile",
    countryCode: "cl",
    locale: "en-CL",
  },
  {
    code: "CNY",
    symbol: "¥",
    name: "Chinese Yuan",
    country: "China",
    countryCode: "cn",
    locale: "zh-CN",
  },
  {
    code: "COP",
    symbol: "$",
    name: "Colombian Peso",
    country: "Colombia",
    countryCode: "co",
    locale: "en-CO",
  },
  {
    code: "CDF",
    symbol: "FC",
    name: "Congolese Franc",
    country: "Congo - Kinshasa",
    countryCode: "cd",
    locale: "en-CD",
  },
  {
    code: "CRC",
    symbol: "₡",
    name: "Costa Rican Colón",
    country: "Costa Rica",
    countryCode: "cr",
    locale: "en-CR",
  },
  {
    code: "CUP",
    symbol: "$MN",
    name: "Cuban Peso",
    country: "Cuba",
    countryCode: "cu",
    locale: "en-CU",
  },
  {
    code: "CZK",
    symbol: "Kč",
    name: "Czech Koruna",
    country: "Czechia",
    countryCode: "cz",
    locale: "en-CZ",
  },
  {
    code: "DKK",
    symbol: "kr",
    name: "Danish Krone",
    country: "Denmark",
    countryCode: "dk",
    locale: "en-DK",
  },
  {
    code: "DOP",
    symbol: "RD$",
    name: "Dominican Peso",
    country: "Dominican Republic",
    countryCode: "do",
    locale: "en-DO",
  },
  {
    code: "EGP",
    symbol: "£",
    name: "Egyptian Pound",
    country: "Egypt",
    countryCode: "eg",
    locale: "en-EG",
  },
  {
    code: "ETB",
    symbol: "Br",
    name: "Ethiopian Birr",
    country: "Ethiopia",
    countryCode: "et",
    locale: "en-ET",
  },
  {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    country: "European Union",
    countryCode: "eu",
    locale: "de-DE",
  },
  {
    code: "GMD",
    symbol: "D",
    name: "Gambian Dalasi",
    country: "Gambia",
    countryCode: "gm",
    locale: "en-GM",
  },
  {
    code: "GEL",
    symbol: "₾",
    name: "Georgian Lari",
    country: "Georgia",
    countryCode: "ge",
    locale: "en-GE",
  },
  {
    code: "GHS",
    symbol: "₵",
    name: "Ghanaian Cedi",
    country: "Ghana",
    countryCode: "gh",
    locale: "en-GH",
  },
  {
    code: "GTQ",
    symbol: "Q",
    name: "Guatemalan Quetzal",
    country: "Guatemala",
    countryCode: "gt",
    locale: "en-GT",
  },
  {
    code: "GNF",
    symbol: "FG",
    name: "Guinean Franc",
    country: "Guinea",
    countryCode: "gn",
    locale: "en-GN",
  },
  {
    code: "GYD",
    symbol: "$",
    name: "Guyanaese Dollar",
    country: "Guyana",
    countryCode: "gy",
    locale: "en-GY",
  },
  {
    code: "HTG",
    symbol: "G",
    name: "Haitian Gourde",
    country: "Haiti",
    countryCode: "ht",
    locale: "en-HT",
  },
  {
    code: "HKD",
    symbol: "$",
    name: "Hong Kong Dollar",
    country: "Hong Kong SAR China",
    countryCode: "hk",
    locale: "en-HK",
  },
  {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian Forint",
    country: "Hungary",
    countryCode: "hu",
    locale: "en-HU",
  },
  {
    code: "ISK",
    symbol: "kr",
    name: "Icelandic Króna",
    country: "Iceland",
    countryCode: "is",
    locale: "en-IS",
  },
  {
    code: "INR",
    symbol: "₹",
    name: "Indian Rupee",
    country: "India",
    countryCode: "in",
    locale: "en-IN",
  },
  {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    countryCode: "id",
    locale: "en-ID",
  },
  {
    code: "IRR",
    symbol: "﷼",
    name: "Iranian Rial",
    country: "Iran",
    countryCode: "ir",
    locale: "en-IR",
  },
  {
    code: "IQD",
    symbol: "ع.د",
    name: "Iraqi Dinar",
    country: "Iraq",
    countryCode: "iq",
    locale: "en-IQ",
  },
  {
    code: "ILS",
    symbol: "₪",
    name: "Israeli New Shekel",
    country: "Israel",
    countryCode: "il",
    locale: "en-IL",
  },
  {
    code: "JMD",
    symbol: "J$",
    name: "Jamaican Dollar",
    country: "Jamaica",
    countryCode: "jm",
    locale: "en-JM",
  },
  {
    code: "JPY",
    symbol: "¥",
    name: "Japanese Yen",
    country: "Japan",
    countryCode: "jp",
    locale: "ja-JP",
  },
  {
    code: "JOD",
    symbol: "د.أ",
    name: "Jordanian Dinar",
    country: "Jordan",
    countryCode: "jo",
    locale: "en-JO",
  },
  {
    code: "KZT",
    symbol: "₸",
    name: "Kazakhstani Tenge",
    country: "Kazakhstan",
    countryCode: "kz",
    locale: "en-KZ",
  },
  {
    code: "KES",
    symbol: "KSh",
    name: "Kenyan Shilling",
    country: "Kenya",
    countryCode: "ke",
    locale: "en-KE",
  },
  {
    code: "KWD",
    symbol: "د.ك",
    name: "Kuwaiti Dinar",
    country: "Kuwait",
    countryCode: "kw",
    locale: "en-KW",
  },
  {
    code: "KGS",
    symbol: "с",
    name: "Kyrgystani Som",
    country: "Kyrgyzstan",
    countryCode: "kg",
    locale: "en-KG",
  },
  {
    code: "LAK",
    symbol: "₭",
    name: "Laotian Kip",
    country: "Laos",
    countryCode: "la",
    locale: "en-LA",
  },
  {
    code: "LBP",
    symbol: "ل.ل",
    name: "Lebanese Pound",
    country: "Lebanon",
    countryCode: "lb",
    locale: "en-LB",
  },
  {
    code: "LRD",
    symbol: "$",
    name: "Liberian Dollar",
    country: "Liberia",
    countryCode: "lr",
    locale: "en-LR",
  },
  {
    code: "LYD",
    symbol: "ل.د",
    name: "Libyan Dinar",
    country: "Libya",
    countryCode: "ly",
    locale: "en-LY",
  },
  {
    code: "MGA",
    symbol: "Ar",
    name: "Malagasy Ariary",
    country: "Madagascar",
    countryCode: "mg",
    locale: "en-MG",
  },
  {
    code: "MWK",
    symbol: "MK",
    name: "Malawian Kwacha",
    country: "Malawi",
    countryCode: "mw",
    locale: "en-MW",
  },
  {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    countryCode: "my",
    locale: "en-MY",
  },
  {
    code: "MVR",
    symbol: "/-",
    name: "Maldivian Rufiyaa",
    country: "Maldives",
    countryCode: "mv",
    locale: "en-MV",
  },
  {
    code: "MUR",
    symbol: "Rs",
    name: "Mauritian Rupee",
    country: "Mauritius",
    countryCode: "mu",
    locale: "en-MU",
  },
  {
    code: "MXN",
    symbol: "$",
    name: "Mexican Peso",
    country: "Mexico",
    countryCode: "mx",
    locale: "en-MX",
  },
  {
    code: "MDL",
    symbol: "L",
    name: "Moldovan Leu",
    country: "Moldova",
    countryCode: "md",
    locale: "en-MD",
  },
  {
    code: "MNT",
    symbol: "₮",
    name: "Mongolian Tugrik",
    country: "Mongolia",
    countryCode: "mn",
    locale: "en-MN",
  },
  {
    code: "MAD",
    symbol: "MAD",
    name: "Moroccan Dirham",
    country: "Morocco",
    countryCode: "ma",
    locale: "en-MA",
  },
  {
    code: "MZN",
    symbol: "MT",
    name: "Mozambican Metical",
    country: "Mozambique",
    countryCode: "mz",
    locale: "en-MZ",
  },
  {
    code: "MMK",
    symbol: "Ks",
    name: "Myanmar Kyat",
    country: "Myanmar (Burma)",
    countryCode: "mm",
    locale: "en-MM",
  },
  {
    code: "NAD",
    symbol: "$",
    name: "Namibian Dollar",
    country: "Namibia",
    countryCode: "na",
    locale: "en-NA",
  },
  {
    code: "NPR",
    symbol: "Rs",
    name: "Nepalese Rupee",
    country: "Nepal",
    countryCode: "np",
    locale: "ne-NP",
  },
  {
    code: "NZD",
    symbol: "$",
    name: "New Zealand Dollar",
    country: "New Zealand",
    countryCode: "nz",
    locale: "en-NZ",
  },
  {
    code: "NIO",
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    country: "Nicaragua",
    countryCode: "ni",
    locale: "en-NI",
  },
  {
    code: "NGN",
    symbol: "₦",
    name: "Nigerian Naira",
    country: "Nigeria",
    countryCode: "ng",
    locale: "en-NG",
  },
  {
    code: "MKD",
    symbol: "ден",
    name: "Macedonian Denar",
    country: "North Macedonia",
    countryCode: "mk",
    locale: "en-MK",
  },
  {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian Krone",
    country: "Norway",
    countryCode: "no",
    locale: "en-NO",
  },
  {
    code: "OMR",
    symbol: "﷼",
    name: "Omani Rial",
    country: "Oman",
    countryCode: "om",
    locale: "en-OM",
  },
  {
    code: "PKR",
    symbol: "Rs",
    name: "Pakistani Rupee",
    country: "Pakistan",
    countryCode: "pk",
    locale: "en-PK",
  },
  {
    code: "PGK",
    symbol: "K",
    name: "Papua New Guinean Kina",
    country: "Papua New Guinea",
    countryCode: "pg",
    locale: "en-PG",
  },
  {
    code: "PYG",
    symbol: "₲",
    name: "Paraguayan Guarani",
    country: "Paraguay",
    countryCode: "py",
    locale: "en-PY",
  },
  {
    code: "PEN",
    symbol: "S/.",
    name: "Peruvian Sol",
    country: "Peru",
    countryCode: "pe",
    locale: "en-PE",
  },
  {
    code: "PHP",
    symbol: "₱",
    name: "Philippine Peso",
    country: "Philippines",
    countryCode: "ph",
    locale: "en-PH",
  },
  {
    code: "PLN",
    symbol: "zł",
    name: "Polish Zloty",
    country: "Poland",
    countryCode: "pl",
    locale: "en-PL",
  },
  {
    code: "QAR",
    symbol: "﷼",
    name: "Qatari Riyal",
    country: "Qatar",
    countryCode: "qa",
    locale: "en-QA",
  },
  {
    code: "RON",
    symbol: "L",
    name: "Romanian Leu",
    country: "Romania",
    countryCode: "ro",
    locale: "en-RO",
  },
  {
    code: "RUB",
    symbol: "₽",
    name: "Russian Ruble",
    country: "Russia",
    countryCode: "ru",
    locale: "en-RU",
  },
  {
    code: "RWF",
    symbol: "FRw",
    name: "Rwandan Franc",
    country: "Rwanda",
    countryCode: "rw",
    locale: "en-RW",
  },
  {
    code: "SAR",
    symbol: "﷼",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    countryCode: "sa",
    locale: "en-SA",
  },
  {
    code: "XOF",
    symbol: "FCFA",
    name: "West African CFA Franc",
    country: "Senegal",
    countryCode: "sn",
    locale: "en-SN",
  },
  {
    code: "RSD",
    symbol: "Дин.",
    name: "Serbian Dinar",
    country: "Serbia",
    countryCode: "rs",
    locale: "en-RS",
  },
  {
    code: "SCR",
    symbol: "Rs",
    name: "Seychellois Rupee",
    country: "Seychelles",
    countryCode: "sc",
    locale: "en-SC",
  },
  {
    code: "SGD",
    symbol: "$",
    name: "Singapore Dollar",
    country: "Singapore",
    countryCode: "sg",
    locale: "en-SG",
  },
  {
    code: "SOS",
    symbol: "S",
    name: "Somali Shilling",
    country: "Somalia",
    countryCode: "so",
    locale: "en-SO",
  },
  {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    country: "South Africa",
    countryCode: "za",
    locale: "en-ZA",
  },
  {
    code: "KRW",
    symbol: "₩",
    name: "South Korean Won",
    country: "South Korea",
    countryCode: "kr",
    locale: "ko-KR",
  },
  {
    code: "LKR",
    symbol: "Rs",
    name: "Sri Lankan Rupee",
    country: "Sri Lanka",
    countryCode: "lk",
    locale: "si-LK",
  },
  {
    code: "SRD",
    symbol: "$",
    name: "Surinamese Dollar",
    country: "Suriname",
    countryCode: "sr",
    locale: "en-SR",
  },
  {
    code: "SEK",
    symbol: "kr",
    name: "Swedish Krona",
    country: "Sweden",
    countryCode: "se",
    locale: "en-SE",
  },
  {
    code: "CHF",
    symbol: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    countryCode: "ch",
    locale: "en-CH",
  },
  {
    code: "SYP",
    symbol: "LS",
    name: "Syrian Pound",
    country: "Syria",
    countryCode: "sy",
    locale: "en-SY",
  },
  {
    code: "TWD",
    symbol: "NT$",
    name: "New Taiwan Dollar",
    country: "Taiwan",
    countryCode: "tw",
    locale: "en-TW",
  },
  {
    code: "TJS",
    symbol: "SM",
    name: "Tajikistani Somoni",
    country: "Tajikistan",
    countryCode: "tj",
    locale: "en-TJ",
  },
  {
    code: "TZS",
    symbol: "TSh",
    name: "Tanzanian Shilling",
    country: "Tanzania",
    countryCode: "tz",
    locale: "en-TZ",
  },
  {
    code: "THB",
    symbol: "฿",
    name: "Thai Baht",
    country: "Thailand",
    countryCode: "th",
    locale: "en-TH",
  },
  {
    code: "TOP",
    symbol: "T$",
    name: "Tongan Paʻanga",
    country: "Tonga",
    countryCode: "to",
    locale: "en-TO",
  },
  {
    code: "TTD",
    symbol: "TT$",
    name: "Trinidad & Tobago Dollar",
    country: "Trinidad & Tobago",
    countryCode: "tt",
    locale: "en-TT",
  },
  {
    code: "TND",
    symbol: "د.ت",
    name: "Tunisian Dinar",
    country: "Tunisia",
    countryCode: "tn",
    locale: "en-TN",
  },
  {
    code: "TRY",
    symbol: "₺",
    name: "Turkish Lira",
    country: "Türkiye",
    countryCode: "tr",
    locale: "en-TR",
  },
  {
    code: "TMT",
    symbol: "m",
    name: "Turkmenistani Manat",
    country: "Turkmenistan",
    countryCode: "tm",
    locale: "en-TM",
  },
  {
    code: "UGX",
    symbol: "USh",
    name: "Ugandan Shilling",
    country: "Uganda",
    countryCode: "ug",
    locale: "en-UG",
  },
  {
    code: "UAH",
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    country: "Ukraine",
    countryCode: "ua",
    locale: "en-UA",
  },
  {
    code: "AED",
    symbol: "د.إ",
    name: "United Arab Emirates Dirham",
    country: "United Arab Emirates",
    countryCode: "ae",
    locale: "en-AE",
  },
  {
    code: "GBP",
    symbol: "£",
    name: "British Pound",
    country: "United Kingdom",
    countryCode: "gb",
    locale: "en-GB",
  },
  {
    code: "USD",
    symbol: "$",
    name: "US Dollar",
    country: "United States",
    countryCode: "us",
    locale: "en-US",
  },
  {
    code: "UYU",
    symbol: "$U",
    name: "Uruguayan Peso",
    country: "Uruguay",
    countryCode: "uy",
    locale: "en-UY",
  },
  {
    code: "UZS",
    symbol: "UZS",
    name: "Uzbekistani Som",
    country: "Uzbekistan",
    countryCode: "uz",
    locale: "en-UZ",
  },
  {
    code: "VES",
    symbol: "Bs",
    name: "Venezuelan Bolívar",
    country: "Venezuela",
    countryCode: "ve",
    locale: "en-VE",
  },
  {
    code: "VND",
    symbol: "₫",
    name: "Vietnamese Dong",
    country: "Vietnam",
    countryCode: "vn",
    locale: "en-VN",
  },
  {
    code: "YER",
    symbol: "﷼",
    name: "Yemeni Rial",
    country: "Yemen",
    countryCode: "ye",
    locale: "en-YE",
  },
  {
    code: "ZMW",
    symbol: "ZK",
    name: "Zambian Kwacha",
    country: "Zambia",
    countryCode: "zm",
    locale: "en-ZM",
  },
  {
    code: "ZWG",
    symbol: "$ZWL",
    name: "Zimbabwean Gold",
    country: "Zimbabwe",
    countryCode: "zw",
    locale: "en-ZW",
  },
];

/** Lookup by ISO 4217 code. */
export const findCurrency = (code: string): CurrencyOption | undefined =>
  CURRENCY_OPTIONS.find((c) => c.code === code);

/**
 * The one to pick when several currencies print the same symbol.
 *
 * 18 of the currencies below render as "$", so a symbol on its own cannot name
 * one. These are the head of each group — the currency that symbol most often
 * means. They are listed explicitly rather than relying on array order, since
 * CURRENCY_OPTIONS is sorted by country: the first "$" in it is the East
 * Caribbean dollar, which is not what "$" usually means.
 *
 * Every symbol shared by more than one currency has an entry here. Where the
 * group has no obvious head, the larger economy wins — a tie-break has to pick
 * something, and the alternative is whichever country happens to sort first.
 */
const SYMBOL_PRIMARY: Record<string, string> = {
  $: "USD",
  "£": "GBP",
  "¥": "JPY",
  Rs: "NPR",
  kr: "SEK",
  "₩": "KRW",
  // U+FDFC is the generic rial sign — Iran, Oman, Qatar, Saudi Arabia, Yemen.
  "﷼": "SAR",
  // Both CFA francs print "FCFA"; the West African one covers eight countries
  // to the Central African one's six.
  FCFA: "XOF",
  // Honduran lempira, Moldovan leu, Romanian leu.
  L: "RON",
  // Belarusian ruble and Ethiopian birr.
  Br: "ETB",
};

/**
 * Resolve the symbol the API stores back to a currency.
 *
 * Callers should compare symbols before calling this: a business saved as "$"
 * and a device already on CAD agree, because CAD prints "$" too, and switching
 * that device to USD would overwrite a deliberate choice with a guess.
 */
export function findCurrencyBySymbol(
  symbol: string,
): CurrencyOption | undefined {
  const wanted = symbol.trim();
  if (!wanted) return undefined;

  const matches = CURRENCY_OPTIONS.filter((c) => c.symbol === wanted);
  if (matches.length === 0) return undefined;
  if (matches.length === 1) return matches[0];

  const primary = SYMBOL_PRIMARY[wanted];
  return matches.find((c) => c.code === primary) ?? matches[0];
}
