import { CurrencyConfig } from "@/lib/config/store";

/**
 * Every currency the app offers, one row per issuing country.
 *
 * Generated from ICU data (`Intl.DisplayNames` for the names,
 * `Intl.NumberFormat` for the narrow symbols) so spellings and symbols match
 * what the platform itself would print, rather than being hand-typed.
 *
 * `countryCode` is ISO 3166-1 alpha-2, which is what flagcdn keys its flags
 * by. Shared currencies — the euro, the CFA francs, the East Caribbean dollar —
 * appear once under a representative country.
 */
export interface CurrencyOption extends CurrencyConfig {
  /** Currency name, e.g. "Nepalese Rupee". */
  name: string;
  /** Country name, for search and the sub-label. */
  country: string;
  /** ISO 3166-1 alpha-2, lowercased for flagcdn. */
  countryCode: string;
}

export const CURRENCY_OPTIONS: CurrencyOption[] = [
  {
    code: "AFN",
    symbol: "؋",
    name: "Afghan Afghani",
    country: "Afghanistan",
    countryCode: "af",
    locale: "en-AF",
  },
  {
    code: "ALL",
    symbol: "ALL",
    name: "Albanian Lek",
    country: "Albania",
    countryCode: "al",
    locale: "en-AL",
  },
  {
    code: "DZD",
    symbol: "DZD",
    name: "Algerian Dinar",
    country: "Algeria",
    countryCode: "dz",
    locale: "en-DZ",
  },
  {
    code: "AOA",
    symbol: "Kz",
    name: "Angolan Kwanza",
    country: "Angola",
    countryCode: "ao",
    locale: "en-AO",
  },
  {
    code: "XCD",
    symbol: "$",
    name: "East Caribbean Dollar",
    country: "Antigua & Barbuda",
    countryCode: "ag",
    locale: "en-AG",
  },
  {
    code: "ARS",
    symbol: "$",
    name: "Argentine Peso",
    country: "Argentina",
    countryCode: "ar",
    locale: "en-AR",
  },
  {
    code: "AMD",
    symbol: "֏",
    name: "Armenian Dram",
    country: "Armenia",
    countryCode: "am",
    locale: "en-AM",
  },
  {
    code: "AWG",
    symbol: "AWG",
    name: "Aruban Florin",
    country: "Aruba",
    countryCode: "aw",
    locale: "en-AW",
  },
  {
    code: "AUD",
    symbol: "$",
    name: "Australian Dollar",
    country: "Australia",
    countryCode: "au",
    locale: "en-AU",
  },
  {
    code: "AZN",
    symbol: "₼",
    name: "Azerbaijani Manat",
    country: "Azerbaijan",
    countryCode: "az",
    locale: "en-AZ",
  },
  {
    code: "BSD",
    symbol: "$",
    name: "Bahamian Dollar",
    country: "Bahamas",
    countryCode: "bs",
    locale: "en-BS",
  },
  {
    code: "BHD",
    symbol: "BHD",
    name: "Bahraini Dinar",
    country: "Bahrain",
    countryCode: "bh",
    locale: "en-BH",
  },
  {
    code: "BDT",
    symbol: "৳",
    name: "Bangladeshi Taka",
    country: "Bangladesh",
    countryCode: "bd",
    locale: "bn-BD",
  },
  {
    code: "BBD",
    symbol: "$",
    name: "Barbadian Dollar",
    country: "Barbados",
    countryCode: "bb",
    locale: "en-BB",
  },
  {
    code: "BYN",
    symbol: "BYN",
    name: "Belarusian Ruble",
    country: "Belarus",
    countryCode: "by",
    locale: "en-BY",
  },
  {
    code: "BZD",
    symbol: "$",
    name: "Belize Dollar",
    country: "Belize",
    countryCode: "bz",
    locale: "en-BZ",
  },
  {
    code: "BMD",
    symbol: "$",
    name: "Bermudan Dollar",
    country: "Bermuda",
    countryCode: "bm",
    locale: "en-BM",
  },
  {
    code: "BTN",
    symbol: "BTN",
    name: "Bhutanese Ngultrum",
    country: "Bhutan",
    countryCode: "bt",
    locale: "en-BT",
  },
  {
    code: "BOB",
    symbol: "Bs",
    name: "Bolivian Boliviano",
    country: "Bolivia",
    countryCode: "bo",
    locale: "en-BO",
  },
  {
    code: "BAM",
    symbol: "KM",
    name: "Bosnia-Herzegovina Convertible Mark",
    country: "Bosnia & Herzegovina",
    countryCode: "ba",
    locale: "en-BA",
  },
  {
    code: "BWP",
    symbol: "P",
    name: "Botswanan Pula",
    country: "Botswana",
    countryCode: "bw",
    locale: "en-BW",
  },
  {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian Real",
    country: "Brazil",
    countryCode: "br",
    locale: "en-BR",
  },
  {
    code: "BND",
    symbol: "$",
    name: "Brunei Dollar",
    country: "Brunei",
    countryCode: "bn",
    locale: "en-BN",
  },
  {
    code: "BGN",
    symbol: "BGN",
    name: "Bulgarian Lev",
    country: "Bulgaria",
    countryCode: "bg",
    locale: "en-BG",
  },
  {
    code: "BIF",
    symbol: "BIF",
    name: "Burundian Franc",
    country: "Burundi",
    countryCode: "bi",
    locale: "en-BI",
  },
  {
    code: "KHR",
    symbol: "៛",
    name: "Cambodian Riel",
    country: "Cambodia",
    countryCode: "kh",
    locale: "en-KH",
  },
  {
    code: "XAF",
    symbol: "FCFA",
    name: "Central African CFA Franc",
    country: "Cameroon",
    countryCode: "cm",
    locale: "en-CM",
  },
  {
    code: "CAD",
    symbol: "$",
    name: "Canadian Dollar",
    country: "Canada",
    countryCode: "ca",
    locale: "en-CA",
  },
  {
    code: "CVE",
    symbol: "CVE",
    name: "Cape Verdean Escudo",
    country: "Cape Verde",
    countryCode: "cv",
    locale: "en-CV",
  },
  {
    code: "KYD",
    symbol: "$",
    name: "Cayman Islands Dollar",
    country: "Cayman Islands",
    countryCode: "ky",
    locale: "en-KY",
  },
  {
    code: "CLP",
    symbol: "$",
    name: "Chilean Peso",
    country: "Chile",
    countryCode: "cl",
    locale: "en-CL",
  },
  {
    code: "CNY",
    symbol: "¥",
    name: "Chinese Yuan",
    country: "China",
    countryCode: "cn",
    locale: "zh-CN",
  },
  {
    code: "COP",
    symbol: "$",
    name: "Colombian Peso",
    country: "Colombia",
    countryCode: "co",
    locale: "en-CO",
  },
  {
    code: "KMF",
    symbol: "CF",
    name: "Comorian Franc",
    country: "Comoros",
    countryCode: "km",
    locale: "en-KM",
  },
  {
    code: "CDF",
    symbol: "CDF",
    name: "Congolese Franc",
    country: "Congo - Kinshasa",
    countryCode: "cd",
    locale: "en-CD",
  },
  {
    code: "CRC",
    symbol: "₡",
    name: "Costa Rican Colón",
    country: "Costa Rica",
    countryCode: "cr",
    locale: "en-CR",
  },
  {
    code: "CUP",
    symbol: "$",
    name: "Cuban Peso",
    country: "Cuba",
    countryCode: "cu",
    locale: "en-CU",
  },
  {
    code: "CZK",
    symbol: "Kč",
    name: "Czech Koruna",
    country: "Czechia",
    countryCode: "cz",
    locale: "en-CZ",
  },
  {
    code: "DKK",
    symbol: "kr",
    name: "Danish Krone",
    country: "Denmark",
    countryCode: "dk",
    locale: "en-DK",
  },
  {
    code: "DJF",
    symbol: "DJF",
    name: "Djiboutian Franc",
    country: "Djibouti",
    countryCode: "dj",
    locale: "en-DJ",
  },
  {
    code: "DOP",
    symbol: "$",
    name: "Dominican Peso",
    country: "Dominican Republic",
    countryCode: "do",
    locale: "en-DO",
  },
  {
    code: "EGP",
    symbol: "E£",
    name: "Egyptian Pound",
    country: "Egypt",
    countryCode: "eg",
    locale: "en-EG",
  },
  {
    code: "SVC",
    symbol: "SVC",
    name: "Salvadoran Colón",
    country: "El Salvador",
    countryCode: "sv",
    locale: "en-SV",
  },
  {
    code: "ERN",
    symbol: "ERN",
    name: "Eritrean Nakfa",
    country: "Eritrea",
    countryCode: "er",
    locale: "en-ER",
  },
  {
    code: "SZL",
    symbol: "SZL",
    name: "Swazi Lilangeni",
    country: "Eswatini",
    countryCode: "sz",
    locale: "en-SZ",
  },
  {
    code: "ETB",
    symbol: "ETB",
    name: "Ethiopian Birr",
    country: "Ethiopia",
    countryCode: "et",
    locale: "en-ET",
  },
  {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    country: "European Union",
    countryCode: "eu",
    locale: "de-DE",
  },
  {
    code: "FKP",
    symbol: "£",
    name: "Falkland Islands Pound",
    country: "Falkland Islands",
    countryCode: "fk",
    locale: "en-FK",
  },
  {
    code: "FJD",
    symbol: "$",
    name: "Fijian Dollar",
    country: "Fiji",
    countryCode: "fj",
    locale: "en-FJ",
  },
  {
    code: "XPF",
    symbol: "CFPF",
    name: "CFP Franc",
    country: "French Polynesia",
    countryCode: "pf",
    locale: "en-PF",
  },
  {
    code: "GMD",
    symbol: "GMD",
    name: "Gambian Dalasi",
    country: "Gambia",
    countryCode: "gm",
    locale: "en-GM",
  },
  {
    code: "GEL",
    symbol: "₾",
    name: "Georgian Lari",
    country: "Georgia",
    countryCode: "ge",
    locale: "en-GE",
  },
  {
    code: "GHS",
    symbol: "GH₵",
    name: "Ghanaian Cedi",
    country: "Ghana",
    countryCode: "gh",
    locale: "en-GH",
  },
  {
    code: "GIP",
    symbol: "£",
    name: "Gibraltar Pound",
    country: "Gibraltar",
    countryCode: "gi",
    locale: "en-GI",
  },
  {
    code: "GTQ",
    symbol: "Q",
    name: "Guatemalan Quetzal",
    country: "Guatemala",
    countryCode: "gt",
    locale: "en-GT",
  },
  {
    code: "GNF",
    symbol: "FG",
    name: "Guinean Franc",
    country: "Guinea",
    countryCode: "gn",
    locale: "en-GN",
  },
  {
    code: "GYD",
    symbol: "$",
    name: "Guyanaese Dollar",
    country: "Guyana",
    countryCode: "gy",
    locale: "en-GY",
  },
  {
    code: "HTG",
    symbol: "HTG",
    name: "Haitian Gourde",
    country: "Haiti",
    countryCode: "ht",
    locale: "en-HT",
  },
  {
    code: "HNL",
    symbol: "L",
    name: "Honduran Lempira",
    country: "Honduras",
    countryCode: "hn",
    locale: "en-HN",
  },
  {
    code: "HKD",
    symbol: "$",
    name: "Hong Kong Dollar",
    country: "Hong Kong SAR China",
    countryCode: "hk",
    locale: "en-HK",
  },
  {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian Forint",
    country: "Hungary",
    countryCode: "hu",
    locale: "en-HU",
  },
  {
    code: "ISK",
    symbol: "kr",
    name: "Icelandic Króna",
    country: "Iceland",
    countryCode: "is",
    locale: "en-IS",
  },
  {
    code: "INR",
    symbol: "₹",
    name: "Indian Rupee",
    country: "India",
    countryCode: "in",
    locale: "en-IN",
  },
  {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian Rupiah",
    country: "Indonesia",
    countryCode: "id",
    locale: "en-ID",
  },
  {
    code: "IRR",
    symbol: "IRR",
    name: "Iranian Rial",
    country: "Iran",
    countryCode: "ir",
    locale: "en-IR",
  },
  {
    code: "IQD",
    symbol: "IQD",
    name: "Iraqi Dinar",
    country: "Iraq",
    countryCode: "iq",
    locale: "en-IQ",
  },
  {
    code: "ILS",
    symbol: "₪",
    name: "Israeli New Shekel",
    country: "Israel",
    countryCode: "il",
    locale: "en-IL",
  },
  {
    code: "JMD",
    symbol: "$",
    name: "Jamaican Dollar",
    country: "Jamaica",
    countryCode: "jm",
    locale: "en-JM",
  },
  {
    code: "JPY",
    symbol: "¥",
    name: "Japanese Yen",
    country: "Japan",
    countryCode: "jp",
    locale: "ja-JP",
  },
  {
    code: "JOD",
    symbol: "JOD",
    name: "Jordanian Dinar",
    country: "Jordan",
    countryCode: "jo",
    locale: "en-JO",
  },
  {
    code: "KZT",
    symbol: "₸",
    name: "Kazakhstani Tenge",
    country: "Kazakhstan",
    countryCode: "kz",
    locale: "en-KZ",
  },
  {
    code: "KES",
    symbol: "KES",
    name: "Kenyan Shilling",
    country: "Kenya",
    countryCode: "ke",
    locale: "en-KE",
  },
  {
    code: "KWD",
    symbol: "KWD",
    name: "Kuwaiti Dinar",
    country: "Kuwait",
    countryCode: "kw",
    locale: "en-KW",
  },
  {
    code: "KGS",
    symbol: "⃀",
    name: "Kyrgystani Som",
    country: "Kyrgyzstan",
    countryCode: "kg",
    locale: "en-KG",
  },
  {
    code: "LAK",
    symbol: "₭",
    name: "Laotian Kip",
    country: "Laos",
    countryCode: "la",
    locale: "en-LA",
  },
  {
    code: "LBP",
    symbol: "L£",
    name: "Lebanese Pound",
    country: "Lebanon",
    countryCode: "lb",
    locale: "en-LB",
  },
  {
    code: "LSL",
    symbol: "LSL",
    name: "Lesotho Loti",
    country: "Lesotho",
    countryCode: "ls",
    locale: "en-LS",
  },
  {
    code: "LRD",
    symbol: "$",
    name: "Liberian Dollar",
    country: "Liberia",
    countryCode: "lr",
    locale: "en-LR",
  },
  {
    code: "LYD",
    symbol: "LYD",
    name: "Libyan Dinar",
    country: "Libya",
    countryCode: "ly",
    locale: "en-LY",
  },
  {
    code: "MOP",
    symbol: "MOP",
    name: "Macanese Pataca",
    country: "Macao SAR China",
    countryCode: "mo",
    locale: "en-MO",
  },
  {
    code: "MGA",
    symbol: "Ar",
    name: "Malagasy Ariary",
    country: "Madagascar",
    countryCode: "mg",
    locale: "en-MG",
  },
  {
    code: "MWK",
    symbol: "MWK",
    name: "Malawian Kwacha",
    country: "Malawi",
    countryCode: "mw",
    locale: "en-MW",
  },
  {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian Ringgit",
    country: "Malaysia",
    countryCode: "my",
    locale: "en-MY",
  },
  {
    code: "MVR",
    symbol: "MVR",
    name: "Maldivian Rufiyaa",
    country: "Maldives",
    countryCode: "mv",
    locale: "en-MV",
  },
  {
    code: "MRU",
    symbol: "MRU",
    name: "Mauritanian Ouguiya",
    country: "Mauritania",
    countryCode: "mr",
    locale: "en-MR",
  },
  {
    code: "MUR",
    symbol: "Rs",
    name: "Mauritian Rupee",
    country: "Mauritius",
    countryCode: "mu",
    locale: "en-MU",
  },
  {
    code: "MXN",
    symbol: "$",
    name: "Mexican Peso",
    country: "Mexico",
    countryCode: "mx",
    locale: "en-MX",
  },
  {
    code: "MDL",
    symbol: "MDL",
    name: "Moldovan Leu",
    country: "Moldova",
    countryCode: "md",
    locale: "en-MD",
  },
  {
    code: "MNT",
    symbol: "₮",
    name: "Mongolian Tugrik",
    country: "Mongolia",
    countryCode: "mn",
    locale: "en-MN",
  },
  {
    code: "MAD",
    symbol: "MAD",
    name: "Moroccan Dirham",
    country: "Morocco",
    countryCode: "ma",
    locale: "en-MA",
  },
  {
    code: "MZN",
    symbol: "MZN",
    name: "Mozambican Metical",
    country: "Mozambique",
    countryCode: "mz",
    locale: "en-MZ",
  },
  {
    code: "MMK",
    symbol: "K",
    name: "Myanmar Kyat",
    country: "Myanmar (Burma)",
    countryCode: "mm",
    locale: "en-MM",
  },
  {
    code: "NAD",
    symbol: "$",
    name: "Namibian Dollar",
    country: "Namibia",
    countryCode: "na",
    locale: "en-NA",
  },
  {
    code: "NPR",
    symbol: "Rs",
    name: "Nepalese Rupee",
    country: "Nepal",
    countryCode: "np",
    locale: "ne-NP",
  },
  {
    code: "NZD",
    symbol: "$",
    name: "New Zealand Dollar",
    country: "New Zealand",
    countryCode: "nz",
    locale: "en-NZ",
  },
  {
    code: "NIO",
    symbol: "C$",
    name: "Nicaraguan Córdoba",
    country: "Nicaragua",
    countryCode: "ni",
    locale: "en-NI",
  },
  {
    code: "NGN",
    symbol: "₦",
    name: "Nigerian Naira",
    country: "Nigeria",
    countryCode: "ng",
    locale: "en-NG",
  },
  {
    code: "KPW",
    symbol: "₩",
    name: "North Korean Won",
    country: "North Korea",
    countryCode: "kp",
    locale: "en-KP",
  },
  {
    code: "MKD",
    symbol: "MKD",
    name: "Macedonian Denar",
    country: "North Macedonia",
    countryCode: "mk",
    locale: "en-MK",
  },
  {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian Krone",
    country: "Norway",
    countryCode: "no",
    locale: "en-NO",
  },
  {
    code: "OMR",
    symbol: "OMR",
    name: "Omani Rial",
    country: "Oman",
    countryCode: "om",
    locale: "en-OM",
  },
  {
    code: "PKR",
    symbol: "Rs",
    name: "Pakistani Rupee",
    country: "Pakistan",
    countryCode: "pk",
    locale: "en-PK",
  },
  {
    code: "PAB",
    symbol: "PAB",
    name: "Panamanian Balboa",
    country: "Panama",
    countryCode: "pa",
    locale: "en-PA",
  },
  {
    code: "PGK",
    symbol: "PGK",
    name: "Papua New Guinean Kina",
    country: "Papua New Guinea",
    countryCode: "pg",
    locale: "en-PG",
  },
  {
    code: "PYG",
    symbol: "₲",
    name: "Paraguayan Guarani",
    country: "Paraguay",
    countryCode: "py",
    locale: "en-PY",
  },
  {
    code: "PEN",
    symbol: "PEN",
    name: "Peruvian Sol",
    country: "Peru",
    countryCode: "pe",
    locale: "en-PE",
  },
  {
    code: "PHP",
    symbol: "₱",
    name: "Philippine Peso",
    country: "Philippines",
    countryCode: "ph",
    locale: "en-PH",
  },
  {
    code: "PLN",
    symbol: "zł",
    name: "Polish Zloty",
    country: "Poland",
    countryCode: "pl",
    locale: "en-PL",
  },
  {
    code: "QAR",
    symbol: "QAR",
    name: "Qatari Riyal",
    country: "Qatar",
    countryCode: "qa",
    locale: "en-QA",
  },
  {
    code: "RON",
    symbol: "lei",
    name: "Romanian Leu",
    country: "Romania",
    countryCode: "ro",
    locale: "en-RO",
  },
  {
    code: "RUB",
    symbol: "₽",
    name: "Russian Ruble",
    country: "Russia",
    countryCode: "ru",
    locale: "en-RU",
  },
  {
    code: "RWF",
    symbol: "RF",
    name: "Rwandan Franc",
    country: "Rwanda",
    countryCode: "rw",
    locale: "en-RW",
  },
  {
    code: "WST",
    symbol: "WST",
    name: "Samoan Tala",
    country: "Samoa",
    countryCode: "ws",
    locale: "en-WS",
  },
  {
    code: "STN",
    symbol: "Db",
    name: "São Tomé & Príncipe Dobra",
    country: "São Tomé & Príncipe",
    countryCode: "st",
    locale: "en-ST",
  },
  {
    code: "SAR",
    symbol: "SAR",
    name: "Saudi Riyal",
    country: "Saudi Arabia",
    countryCode: "sa",
    locale: "en-SA",
  },
  {
    code: "XOF",
    symbol: "F CFA",
    name: "West African CFA Franc",
    country: "Senegal",
    countryCode: "sn",
    locale: "en-SN",
  },
  {
    code: "RSD",
    symbol: "RSD",
    name: "Serbian Dinar",
    country: "Serbia",
    countryCode: "rs",
    locale: "en-RS",
  },
  {
    code: "SCR",
    symbol: "SCR",
    name: "Seychellois Rupee",
    country: "Seychelles",
    countryCode: "sc",
    locale: "en-SC",
  },
  {
    code: "SLE",
    symbol: "SLE",
    name: "Sierra Leonean Leone",
    country: "Sierra Leone",
    countryCode: "sl",
    locale: "en-SL",
  },
  {
    code: "SGD",
    symbol: "$",
    name: "Singapore Dollar",
    country: "Singapore",
    countryCode: "sg",
    locale: "en-SG",
  },
  {
    code: "SBD",
    symbol: "$",
    name: "Solomon Islands Dollar",
    country: "Solomon Islands",
    countryCode: "sb",
    locale: "en-SB",
  },
  {
    code: "SOS",
    symbol: "SOS",
    name: "Somali Shilling",
    country: "Somalia",
    countryCode: "so",
    locale: "en-SO",
  },
  {
    code: "ZAR",
    symbol: "R",
    name: "South African Rand",
    country: "South Africa",
    countryCode: "za",
    locale: "en-ZA",
  },
  {
    code: "KRW",
    symbol: "₩",
    name: "South Korean Won",
    country: "South Korea",
    countryCode: "kr",
    locale: "ko-KR",
  },
  {
    code: "SSP",
    symbol: "£",
    name: "South Sudanese Pound",
    country: "South Sudan",
    countryCode: "ss",
    locale: "en-SS",
  },
  {
    code: "LKR",
    symbol: "Rs",
    name: "Sri Lankan Rupee",
    country: "Sri Lanka",
    countryCode: "lk",
    locale: "si-LK",
  },
  {
    code: "SHP",
    symbol: "£",
    name: "St. Helena Pound",
    country: "St. Helena",
    countryCode: "sh",
    locale: "en-SH",
  },
  {
    code: "SDG",
    symbol: "SDG",
    name: "Sudanese Pound",
    country: "Sudan",
    countryCode: "sd",
    locale: "en-SD",
  },
  {
    code: "SRD",
    symbol: "$",
    name: "Surinamese Dollar",
    country: "Suriname",
    countryCode: "sr",
    locale: "en-SR",
  },
  {
    code: "SEK",
    symbol: "kr",
    name: "Swedish Krona",
    country: "Sweden",
    countryCode: "se",
    locale: "en-SE",
  },
  {
    code: "CHF",
    symbol: "CHF",
    name: "Swiss Franc",
    country: "Switzerland",
    countryCode: "ch",
    locale: "en-CH",
  },
  {
    code: "SYP",
    symbol: "£",
    name: "Syrian Pound",
    country: "Syria",
    countryCode: "sy",
    locale: "en-SY",
  },
  {
    code: "TWD",
    symbol: "$",
    name: "New Taiwan Dollar",
    country: "Taiwan",
    countryCode: "tw",
    locale: "en-TW",
  },
  {
    code: "TJS",
    symbol: "TJS",
    name: "Tajikistani Somoni",
    country: "Tajikistan",
    countryCode: "tj",
    locale: "en-TJ",
  },
  {
    code: "TZS",
    symbol: "TZS",
    name: "Tanzanian Shilling",
    country: "Tanzania",
    countryCode: "tz",
    locale: "en-TZ",
  },
  {
    code: "THB",
    symbol: "฿",
    name: "Thai Baht",
    country: "Thailand",
    countryCode: "th",
    locale: "en-TH",
  },
  {
    code: "TOP",
    symbol: "T$",
    name: "Tongan Paʻanga",
    country: "Tonga",
    countryCode: "to",
    locale: "en-TO",
  },
  {
    code: "TTD",
    symbol: "$",
    name: "Trinidad & Tobago Dollar",
    country: "Trinidad & Tobago",
    countryCode: "tt",
    locale: "en-TT",
  },
  {
    code: "TND",
    symbol: "TND",
    name: "Tunisian Dinar",
    country: "Tunisia",
    countryCode: "tn",
    locale: "en-TN",
  },
  {
    code: "TRY",
    symbol: "₺",
    name: "Turkish Lira",
    country: "Türkiye",
    countryCode: "tr",
    locale: "en-TR",
  },
  {
    code: "TMT",
    symbol: "TMT",
    name: "Turkmenistani Manat",
    country: "Turkmenistan",
    countryCode: "tm",
    locale: "en-TM",
  },
  {
    code: "UGX",
    symbol: "UGX",
    name: "Ugandan Shilling",
    country: "Uganda",
    countryCode: "ug",
    locale: "en-UG",
  },
  {
    code: "UAH",
    symbol: "₴",
    name: "Ukrainian Hryvnia",
    country: "Ukraine",
    countryCode: "ua",
    locale: "en-UA",
  },
  {
    code: "AED",
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    country: "United Arab Emirates",
    countryCode: "ae",
    locale: "en-AE",
  },
  {
    code: "GBP",
    symbol: "£",
    name: "British Pound",
    country: "United Kingdom",
    countryCode: "gb",
    locale: "en-GB",
  },
  {
    code: "USD",
    symbol: "$",
    name: "US Dollar",
    country: "United States",
    countryCode: "us",
    locale: "en-US",
  },
  {
    code: "UYU",
    symbol: "$",
    name: "Uruguayan Peso",
    country: "Uruguay",
    countryCode: "uy",
    locale: "en-UY",
  },
  {
    code: "UZS",
    symbol: "UZS",
    name: "Uzbekistani Som",
    country: "Uzbekistan",
    countryCode: "uz",
    locale: "en-UZ",
  },
  {
    code: "VUV",
    symbol: "VUV",
    name: "Vanuatu Vatu",
    country: "Vanuatu",
    countryCode: "vu",
    locale: "en-VU",
  },
  {
    code: "VES",
    symbol: "VES",
    name: "Venezuelan Bolívar",
    country: "Venezuela",
    countryCode: "ve",
    locale: "en-VE",
  },
  {
    code: "VND",
    symbol: "₫",
    name: "Vietnamese Dong",
    country: "Vietnam",
    countryCode: "vn",
    locale: "en-VN",
  },
  {
    code: "YER",
    symbol: "YER",
    name: "Yemeni Rial",
    country: "Yemen",
    countryCode: "ye",
    locale: "en-YE",
  },
  {
    code: "ZMW",
    symbol: "ZK",
    name: "Zambian Kwacha",
    country: "Zambia",
    countryCode: "zm",
    locale: "en-ZM",
  },
  {
    code: "ZWG",
    symbol: "ZWG",
    name: "Zimbabwean Gold",
    country: "Zimbabwe",
    countryCode: "zw",
    locale: "en-ZW",
  },
];

/** Lookup by ISO 4217 code. */
export const findCurrency = (code: string): CurrencyOption | undefined =>
  CURRENCY_OPTIONS.find((c) => c.code === code);

/**
 * What a shared symbol most likely means.
 *
 * Symbols are far from unique — 29 currencies here print as "$" — so a symbol
 * alone cannot identify one. These are the fallbacks for a device with no
 * local choice to go on; "Rs" resolves to NPR because that is this app's home
 * currency, not because it is alphabetically first.
 */
const SYMBOL_PRIMARY: Record<string, string> = {
  $: "USD",
  "£": "GBP",
  "¥": "JPY",
  Rs: "NPR",
  kr: "SEK",
  "₩": "KRW",
};

/**
 * Resolve the symbol the API stores back to a currency.
 *
 * `preferredCode` wins whenever it is among the matches — it is the code
 * already in play locally, i.e. what this user last chose. Without it, a
 * business saved as "$" would be read back as whichever dollar happened to
 * sort first.
 */
export function findCurrencyBySymbol(
  symbol: string,
  preferredCode?: string,
): CurrencyOption | undefined {
  const wanted = symbol.trim();
  if (!wanted) return undefined;

  const matches = CURRENCY_OPTIONS.filter((c) => c.symbol === wanted);
  if (matches.length === 0) return undefined;
  if (matches.length === 1) return matches[0];

  const preferred = preferredCode
    ? matches.find((c) => c.code === preferredCode)
    : undefined;
  if (preferred) return preferred;

  const primary = SYMBOL_PRIMARY[wanted];
  return matches.find((c) => c.code === primary) ?? matches[0];
}
