"use client";

import { useMemo, useState } from "react";
import { useCurrency } from "@/providers/CurrencyContext";
import { formatCurrencySymbol } from "@/utils/helper";
import { Landmark } from "lucide-react";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from "recharts";
import type {
  NameType,
  Payload,
  ValueType,
} from "recharts/types/component/DefaultTooltipContent";
import RangeBadge from "@/components/ui/RangeBadge";
import {
  AXIS_TICK,
  CHART_PALETTE,
  ChartCard,
  ChartPager,
  ChartTooltipBox,
} from "../chartCard";
import { TaxRankedChartSkeleton } from "./TaxAnalyticsSkeletons";

interface TaxableItem {
  name: string;
  totalTaxAmount: number;
  transactionCount: number;
}

interface ChartDatum {
  name: string;
  amount: number;
  count: number;
  rank: number;
}

const PAGE_SIZE = 5;
const CHART_COLORS = ["#3B82F6", "#60A5FA", "#93C5FD", "#BFDBFE"];
const TOP_COLOR = "#F59E0B";

const colorForRank = (rank: number, idx: number): string =>
  rank === 0 ? TOP_COLOR : CHART_COLORS[idx % CHART_COLORS.length];

const CustomTooltip = ({
  active,
  payload,
}: {
  active?: boolean;
  payload?: Payload<ValueType, NameType>[];
}) => {
  const { currency } = useCurrency();
  if (!active || !payload?.length) return null;

  const item = payload[0].payload as ChartDatum;
  const color = colorForRank(item.rank, item.rank % PAGE_SIZE);
  return (
    <ChartTooltipBox
      label={`#${item.rank + 1} · ${item.name}`}
      rows={[
        {
          name: "Tax generated",
          color,
          value: formatCurrencySymbol(
            item.amount,
            currency.symbol,
            currency.locale,
          ),
        },
        {
          name: "Order count",
          color,
          value: item.count.toLocaleString(),
        },
      ]}
    />
  );
};

/** One figure in the strip above the chart. */
function Total({ label, value }: { label: string; value: string }) {
  return (
    <div className="min-w-0">
      <p className="text-[11px]" style={{ color: CHART_PALETTE.subtitle }}>
        {label}
      </p>
      <p
        className="truncate text-base font-semibold tracking-tight tabular-nums"
        style={{ color: CHART_PALETTE.title }}
      >
        {value}
      </p>
    </div>
  );
}

const HighestTaxGenerated = ({
  data,
  isLoading,
  isError,
}: {
  data: TaxableItem[];
  isLoading: boolean;
  isError: boolean;
}) => {
  const { currency } = useCurrency();
  const [page, setPage] = useState(0);

  const fmt = (v: number) =>
    formatCurrencySymbol(v, currency.symbol, currency.locale);

  // Highest tax-generating items first (all items, not just the top 5).
  const sorted = useMemo(
    () => [...data].sort((a, b) => b.totalTaxAmount - a.totalTaxAmount),
    [data],
  );

  // Reset to the first page whenever the dataset changes (e.g. date filter).
  // Render-time reset avoids a setState-in-effect cascade; `sorted` is stable
  // (memoized on `data`) so this only fires when the data actually changes.
  const [prevSorted, setPrevSorted] = useState(sorted);
  if (prevSorted !== sorted) {
    setPrevSorted(sorted);
    setPage(0);
  }

  const { totalTax, totalTransactions } = useMemo(
    () => ({
      totalTax: sorted.reduce((sum, i) => sum + i.totalTaxAmount, 0),
      totalTransactions: sorted.reduce((sum, i) => sum + i.transactionCount, 0),
    }),
    [sorted],
  );

  const totalPages = Math.max(1, Math.ceil(sorted.length / PAGE_SIZE));
  const safePage = Math.min(page, totalPages - 1);

  // Chart data for the current page, carrying the global rank + transactions.
  const chartData = useMemo<ChartDatum[]>(
    () =>
      sorted
        .slice(safePage * PAGE_SIZE, safePage * PAGE_SIZE + PAGE_SIZE)
        .map((item, idx) => ({
          name: item.name,
          amount: item.totalTaxAmount,
          count: item.transactionCount,
          rank: safePage * PAGE_SIZE + idx,
        })),
    [sorted, safePage],
  );

  const showPager = !isLoading && !isError && totalPages > 1;

  return (
    <ChartCard
      icon={Landmark}
      // Amber, as before: Tailwind's amber-600 / amber-200 / amber-50.
      iconColor="#d97706"
      iconBorder="#fde68a"
      iconBg="#fffbeb"
      title="Highest Tax Generated By Products"
      info={{
        heading: "Reading this chart",
        // From useHighestTaxGenerated: per-product tax over the page's range.
        body: "Products ranked by the tax they generated over the date range at the top of the page, five at a time, highest first. The leader is picked out in amber. Order count is how many bills the product appeared on.",
      }}
      subtitle="Tax Generated by the products"
      controls={
        <>
          <RangeBadge variant="pill" />
          {showPager && (
            <ChartPager
              first={safePage * PAGE_SIZE + 1}
              last={Math.min((safePage + 1) * PAGE_SIZE, sorted.length)}
              total={sorted.length}
              onPrev={() => setPage((p) => Math.max(0, p - 1))}
              onNext={() => setPage((p) => Math.min(totalPages - 1, p + 1))}
              itemLabel="products"
            />
          )}
        </>
      }
      className="h-full"
    >
      {isLoading ? (
        <TaxRankedChartSkeleton />
      ) : isError ? (
        <p
          className="py-16 text-center text-sm"
          style={{ color: CHART_PALETTE.bad }}
        >
          Failed to load Highest Tax Generated
        </p>
      ) : sorted.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-12">
          <div
            className="mb-3 flex h-16 w-16 items-center justify-center rounded-full"
            style={{ backgroundColor: CHART_PALETTE.hover }}
          >
            <Landmark size={24} style={{ color: CHART_PALETTE.subtitle }} />
          </div>
          <p className="text-sm" style={{ color: CHART_PALETTE.title }}>
            No highest tax generated data
          </p>
          <p className="mt-1 text-xs" style={{ color: CHART_PALETTE.subtitle }}>
            Highest Tax Generated data will appear here
          </p>
        </div>
      ) : (
        <>
          {/* Totals — the figures behind the ranking, above the chart */}
          <div className="mb-4 flex items-center justify-between gap-3">
            <Total label="Total tax generated" value={fmt(totalTax)} />
            <div
              className="h-8 w-px"
              style={{ backgroundColor: CHART_PALETTE.grid }}
            />
            <div className="flex shrink-0 items-center gap-3 text-right">
              <Total label="Items" value={sorted.length.toLocaleString()} />
              <div
                className="hidden h-8 w-px sm:block"
                style={{ backgroundColor: CHART_PALETTE.grid }}
              />
              <div className="hidden sm:block">
                <Total
                  label="Items order count"
                  value={totalTransactions.toLocaleString()}
                />
              </div>
            </div>
          </div>

          {/* Horizontal bar chart (current page) */}
          <div style={{ height: Math.max(chartData.length * 44, 120) }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={chartData}
                layout="vertical"
                margin={{ top: 0, right: 10, left: 0, bottom: 0 }}
                barCategoryGap="20%"
              >
                <CartesianGrid
                  horizontal={false}
                  stroke={CHART_PALETTE.grid}
                  strokeDasharray="3 3"
                />
                <XAxis
                  type="number"
                  axisLine={false}
                  tickLine={false}
                  tick={AXIS_TICK}
                  tickFormatter={(v: number) =>
                    v >= 1000 ? `${(v / 1000).toFixed(0)}k` : `${v}`
                  }
                />
                <YAxis
                  dataKey="name"
                  type="category"
                  axisLine={false}
                  tickLine={false}
                  tick={AXIS_TICK}
                  width={90}
                  tickFormatter={(val: string) =>
                    val.length > 11 ? val.slice(0, 10) + "…" : val
                  }
                />
                <Tooltip
                  content={<CustomTooltip />}
                  cursor={{ fill: CHART_PALETTE.hover }}
                />
                <Bar
                  dataKey="amount"
                  name="Tax generated"
                  radius={[0, 4, 4, 0]}
                >
                  {chartData.map((d, index) => (
                    <Cell key={index} fill={colorForRank(d.rank, index)} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </>
      )}
    </ChartCard>
  );
};

export default HighestTaxGenerated;
