"use client";

import { useMemo, useState } from "react";
import { useCurrency } from "@/providers/CurrencyContext";
import { formatCurrencySymbol } from "@/utils/helper";
import { ChartPie } from "lucide-react";
import type { CategoryTax } from "@/hooks/useTaxByCategory";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
} from "recharts";
import type {
  NameType,
  Payload,
  ValueType,
} from "recharts/types/component/DefaultTooltipContent";
import RangeBadge from "@/components/ui/RangeBadge";
import {
  AXIS_TICK,
  CHART_PALETTE,
  ChartCard,
  ChartPager,
  ChartTooltipBox,
} from "../chartCard";
import { TaxRankedChartSkeleton } from "./TaxAnalyticsSkeletons";

const BRIGHT_COLORS = [
  "#EF4444", // bright red
  "#10B981", // emerald
  "#3B82F6", // blue
  "#8B5CF6", // violet
  "#F59E0B", // amber
  "#EC4899", // pink
  "#14B8A6", // teal
  "#F97316", // orange
  "#6366F1", // indigo
  "#84CC16", // lime
];

interface ChartDatum {
  name: string;
  amount: number;
  productCount: number;
  rank: number;
}

const PAGE_SIZE = 5;

const CustomTooltip = ({
  active,
  payload,
}: {
  active?: boolean;
  payload?: Payload<ValueType, NameType>[];
}) => {
  const { currency } = useCurrency();
  if (!active || !payload?.length) return null;

  const item = payload[0].payload as ChartDatum;
  const color = BRIGHT_COLORS[(item.rank % PAGE_SIZE) % BRIGHT_COLORS.length];
  return (
    <ChartTooltipBox
      label={`#${item.rank + 1} · ${item.name}`}
      rows={[
        {
          name: "Tax",
          color,
          value: formatCurrencySymbol(
            item.amount,
            currency.symbol,
            currency.locale,
          ),
        },
        {
          name: "Products",
          color,
          value: item.productCount.toLocaleString(),
        },
      ]}
    />
  );
};

/** One figure in the strip above the chart. */
function Total({ label, value }: { label: string; value: string }) {
  return (
    <div className="min-w-0">
      <p className="text-[11px]" style={{ color: CHART_PALETTE.subtitle }}>
        {label}
      </p>
      <p
        className="truncate text-base font-semibold tracking-tight tabular-nums"
        style={{ color: CHART_PALETTE.title }}
      >
        {value}
      </p>
    </div>
  );
}

const TaxByCategory = ({
  data,
  isLoading,
  isError,
}: {
  data: CategoryTax[];
  isLoading: boolean;
  isError: boolean;
}) => {
  const { currency } = useCurrency();
  const [page, setPage] = useState(0);

  const fmt = (v: number) =>
    formatCurrencySymbol(v, currency.symbol, currency.locale);

  // Already sorted by totalTax descending from the hook
  const sorted = useMemo(() => data, [data]);

  // Reset to the first page whenever the dataset changes
  const [prevSorted, setPrevSorted] = useState(sorted);
  if (prevSorted !== sorted) {
    setPrevSorted(sorted);
    setPage(0);
  }

  const { totalTax, totalCategories } = useMemo(
    () => ({
      totalTax: sorted.reduce((sum, i) => sum + i.totalTax, 0),
      totalCategories: sorted.length,
    }),
    [sorted],
  );

  const totalPages = Math.max(1, Math.ceil(sorted.length / PAGE_SIZE));
  const safePage = Math.min(page, totalPages - 1);

  // Chart data for the current page, carrying the global rank + productCount + color
  const chartData = useMemo<ChartDatum[]>(
    () =>
      sorted
        .slice(safePage * PAGE_SIZE, safePage * PAGE_SIZE + PAGE_SIZE)
        .map((item, idx) => ({
          name: item.categoryName,
          amount: item.totalTax,
          productCount: item.productCount,
          rank: safePage * PAGE_SIZE + idx,
        })),
    [sorted, safePage],
  );

  const showPager = !isLoading && !isError && totalPages > 1;

  return (
    <ChartCard
      icon={ChartPie}
      // Sky, as before: Tailwind's sky-600 / sky-200 / sky-50.
      iconColor="#0284c7"
      iconBorder="#bae6fd"
      iconBg="#f0f9ff"
      title="Tax by Category"
      info={{
        heading: "Reading this chart",
        // From useTaxByCategory: product categories over the page's range.
        body: "Product categories ranked by the tax they generated over the date range at the top of the page, five at a time, highest first. Products counts how many products in that category were sold in the range.",
      }}
      subtitle="Tax Generated by various product categories"
      controls={
        <>
          <RangeBadge variant="pill" />
          {showPager && (
            <ChartPager
              first={safePage * PAGE_SIZE + 1}
              last={Math.min((safePage + 1) * PAGE_SIZE, sorted.length)}
              total={sorted.length}
              onPrev={() => setPage((p) => Math.max(0, p - 1))}
              onNext={() => setPage((p) => Math.min(totalPages - 1, p + 1))}
              itemLabel="categories"
            />
          )}
        </>
      }
      className="h-full"
    >
      {isLoading ? (
        <TaxRankedChartSkeleton />
      ) : isError ? (
        <p
          className="py-16 text-center text-sm"
          style={{ color: CHART_PALETTE.bad }}
        >
          Failed to load category tax data
        </p>
      ) : sorted.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-12">
          <div
            className="mb-3 flex h-16 w-16 items-center justify-center rounded-full"
            style={{ backgroundColor: CHART_PALETTE.hover }}
          >
            <ChartPie size={24} style={{ color: CHART_PALETTE.subtitle }} />
          </div>
          <p className="text-sm" style={{ color: CHART_PALETTE.title }}>
            No tax by category data
          </p>
          <p className="mt-1 text-xs" style={{ color: CHART_PALETTE.subtitle }}>
            Tax by Category data will appear here
          </p>
        </div>
      ) : (
        <>
          {/* Totals — the figures behind the ranking, above the chart */}
          <div className="mb-4 flex items-center justify-between gap-3">
            <Total label="Total tax by category" value={fmt(totalTax)} />
            <div
              className="h-8 w-px"
              style={{ backgroundColor: CHART_PALETTE.grid }}
            />
            <div className="shrink-0 text-right">
              <Total
                label="Categories"
                value={totalCategories.toLocaleString()}
              />
            </div>
          </div>

          {/* Horizontal bar chart (current page) */}
          <div style={{ height: Math.max(chartData.length * 44, 120) }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={chartData}
                layout="vertical"
                margin={{ top: 0, right: 10, left: 0, bottom: 0 }}
                barCategoryGap="20%"
              >
                <CartesianGrid
                  horizontal={false}
                  stroke={CHART_PALETTE.grid}
                  strokeDasharray="3 3"
                />
                <XAxis
                  type="number"
                  axisLine={false}
                  tickLine={false}
                  tick={AXIS_TICK}
                  tickFormatter={(v: number) =>
                    v >= 1000 ? `${(v / 1000).toFixed(0)}k` : `${v}`
                  }
                />
                <YAxis
                  dataKey="name"
                  type="category"
                  axisLine={false}
                  tickLine={false}
                  tick={AXIS_TICK}
                  width={90}
                  tickFormatter={(val: string) =>
                    val.length > 11 ? val.slice(0, 10) + "…" : val
                  }
                />
                <Tooltip
                  content={<CustomTooltip />}
                  cursor={{ fill: CHART_PALETTE.hover }}
                />
                <Bar dataKey="amount" name="Tax" radius={[0, 4, 4, 0]}>
                  {chartData.map((d, index) => (
                    <Cell
                      key={index}
                      fill={BRIGHT_COLORS[index % BRIGHT_COLORS.length]}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </>
      )}
    </ChartCard>
  );
};

export default TaxByCategory;
